<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RV6F1IE" failures="1" tests="2" name="Data Provider Test" time="69.02" errors="0" timestamp="2022-12-09T00:46:46 IST">
  <testcase classname="clientapp.tests.DataProviderTest" name="DataProviderTestDepends" time="16.757">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at clientapp.tests.DataProviderTest.DataProviderTestDepends(DataProviderTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- DataProviderTestDepends -->
  <testcase classname="clientapp.tests.DataProviderTest" name="submitOrder" time="0.0">
    <skipped/>
  </testcase> <!-- submitOrder -->
</testsuite> <!-- Data Provider Test -->
